name: Quality Assurance

on: 
  push:
    branches:
      - master
      - v4
  pull_request:
    branches:
      - '*'

jobs:
  # test:
  #   name: Ava Testing

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       node-version: [12.x]
        
  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Node
  #       uses: actions/setup-node@v1.4.2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Cache Dependencies
  #       uses: actions/cache@v1.1.2
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         path: ~/.npm
  #         key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-build-${{ env.cache-name }}-
  #           ${{ runner.os }}-build-
  #           ${{ runner.os }}-
  #     - name: Install Dependencies
  #       run: npm i
  #     - name: Run Tests
  #       run: npm test
  #     - name: Upload Coverage
  #       if: success()
  #       uses: codecov/codecov-action@v1.0.6
  #       with:
  #         token: ${{secrets.CODECOV_TOKEN}}
  #         file: ./coverage/lcov.info
  lint:
    name: Linting

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x

    runs-on: ${{ matrix.os }}

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Cache Dependencies
        uses: actions/cache@v1.1.2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      -
        name: Install Dependencies
        run: npm ci
      -
        name: Lint Code
        run: npm run lint
